### ISSUE TITLE
Connection to a local .fdb file not working with docker-compose

### ISSUE THREAD

**Issue by mikenussbaumer** [dcms-world/firebird-docker#4]
Hey :) I found this repository and I think it would solve my problem. 

I want to connect to a .fdb file from my local machine from the firebird server (docker). 💯 

These are my files:
**docker-compose.yml**
```
version: '3'

services:
  firebird-server:
    image: 'dcms/firebird-docker:2.5.6'
    ports:
      - '3050:3050'
      - '3051:3051'
    environment:
      - 'SYSDBAPASS=masterkey1234'
      - 'FIREBIRD_PORT=3050'
      - 'REMOTE_AUX_PORT=3051'
    volumes:
      - './firebird/:/db'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
```

`firebird` directory with `DB1.FDB` in it.

Then I start the application using `docker-compose up` and it seems to work.

## Problem

I want to access the `DB1.FDB` file from a database client (in my case Datagrip) and this seems to not work due to this error:

```
[08001][335544344] I/O error during "open" operation for file "db/DB1.fdb"; 
Error while trying to open file; No such file or directory [SQLState:08001, ISC error code:335544344].
```
![Screenshot 2021-12-06 at 19 09 54](https://user-images.githubusercontent.com/43721860/144899087-dd9874dc-375f-42df-ab4d-92b07c49aad3.png)

I would really appreciate your help 👍
